"""Framework-independent domain layer: vocabulary, models, errors, identifiers."""

from executable_trust.domain.enums import (
    ActorType,
    AuthorizationResult,
    ClaimVerdict,
    DecisionOutcome,
    Environment,
    EvidenceQuality,
    LifecycleState,
    Population,
    RatificationStatus,
    ReasonCode,
    ResponseStrategy,
)
from executable_trust.domain.errors import (
    ContractError,
    ContractNotFound,
    ContractNotRatified,
    ContractValidationError,
    ExecutableTrustError,
    ImmutableRecordViolation,
    InvalidTransition,
    LifecycleError,
    MissingAccountableReview,
    TraceabilityError,
    UncontrolledReasonCode,
    VerifierFailure,
    VerifierTimeout,
    VerifierUnavailable,
)
from executable_trust.domain.identifiers import (
    Clock,
    FixedClock,
    IdFactory,
    SequentialIdFactory,
    SystemClock,
    UuidIdFactory,
)
from executable_trust.domain.models import Actor, Claim, ClaimCounts, TrustRequest

__all__ = [
    "Actor",
    "ActorType",
    "AuthorizationResult",
    "Claim",
    "ClaimCounts",
    "ClaimVerdict",
    "Clock",
    "ContractError",
    "ContractNotFound",
    "ContractNotRatified",
    "ContractValidationError",
    "DecisionOutcome",
    "Environment",
    "EvidenceQuality",
    "ExecutableTrustError",
    "FixedClock",
    "IdFactory",
    "ImmutableRecordViolation",
    "InvalidTransition",
    "LifecycleError",
    "LifecycleState",
    "MissingAccountableReview",
    "Population",
    "RatificationStatus",
    "ReasonCode",
    "ResponseStrategy",
    "SequentialIdFactory",
    "SystemClock",
    "TraceabilityError",
    "TrustRequest",
    "UncontrolledReasonCode",
    "UuidIdFactory",
    "VerifierFailure",
    "VerifierTimeout",
    "VerifierUnavailable",
]
